version: '3.8'

services:
  postgres:
    image: 'postgres:16'
    container_name: 'ServiceForCv-postgres16'
    ports:
      - 5432:5432
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=ServiceForCv-db'