server:
  port: 8085

spring:
  datasource:
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ServiceForCv-postgres16:5432/ServiceForCv-db

  sql:
    init:
      mode: never

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true

minio:
  bucket: files
  url: http://minio:9000
  accessKey: minioadmin
  secretKey: minioadmin